{"name": "test_successful_checkout", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 2.0s, while waiting for:\nbrowser.element(('css selector', '.summary_value_label')).has texts ('Free Pony Express Delivery!',)\n\nReason: TypeError: 'WebElement' object is not iterable\nScreenshot: file://C:\\Users\\skmee\\.selene\\screenshots\\1690626939145\\1690626939146.png\nPageSource: file://C:\\Users\\skmee\\.selene\\screenshots\\1690626939145\\1690626939146.html", "trace": "fn = <selene.core.conditions.CollectionCondition object at 0x000002466E5431D0>\n\n    @self._decorator(self)\n    def _(fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n>               return fn(self.entity)\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\wait.py:122: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selene.core.conditions.CollectionCondition object at 0x000002466E5431D0>\nentity = <selene.core.entity.Element object at 0x000002466E543210>\n\n    def __call__(self, entity: E) -> None:\n>       return self._fn(entity)\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\condition.py:174: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nentity = <selene.core.entity.Element object at 0x000002466E543210>\n\n    def fn(entity: E) -> None:\n        query_to_str = str(query)\n        result = (\n            query.__name__\n            if query_to_str.startswith('<function')\n            else query_to_str\n        )\n>       actual = query(entity)\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\condition.py:145: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncollection = <selene.core.entity.Element object at 0x000002466E543210>\n\n    def visible_texts(collection: Collection) -> List[str]:\n>       return [\n            webelement.text\n            for webelement in collection()\n            if webelement.is_displayed()\n        ]\nE       TypeError: 'WebElement' object is not iterable\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\match.py:393: TypeError\n\nDuring handling of the above exception, another exception occurred:\n\nlogin = <sauce_demo_UI_autotests.model.application.Application object at 0x000002466E249990>\n\n    @allure.tag(\"web\")\n    @allure.feature(f'Successful Checkout with Valid User Information')\n    @allure.story('Verify that a user with valid information can successfully complete the checkout process and reach the '\n                  'order confirmation page.')\n    def test_successful_checkout(login):\n        with allure.step('Navigate to the checkout page and fill in valid user information'):\n            app.checkout_page.open().\\\n                 fill_first_name(user.first_name).\\\n                 fill_last_name(user.last_name).\\\n                 fill_zip_code(user.zip_code).\\\n                 go_to_second_part()\n        with allure.step('Verify that url redirected to second part of checkout'):\n            app.checkout_page.verify_url_redirected()\n        with allure.step('Verify second part consist of payment and delivery information'):\n            app.checkout_page.verify_payment_info().\\\n>               verify_shipping_info().\\\n                verify_item_total_price_is_expected()\n\ntest_checkout_page.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\sauce_demo_UI_autotests\\model\\pages\\checkout_page.py:34: in verify_shipping_info\n    browser.element('.summary_value_label').should(have.texts('Free Pony Express Delivery!'))\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\entity.py:594: in should\n    super().should(condition)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\entity.py:127: in should\n    self.wait.for_(condition)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\wait.py:147: in for_\n    return _(fn)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nfn = <selene.core.conditions.CollectionCondition object at 0x000002466E5431D0>\n\n    @self._decorator(self)\n    def _(fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n                return fn(self.entity)\n            except Exception as reason:\n                if time.time() > finish_time:\n    \n                    reason_message = str(reason)\n    \n                    reason_string = '{name}: {message}'.format(\n                        name=reason.__class__.__name__,\n                        message=reason_message,\n                    )\n                    # todo: think on how can we improve logging failures in selene, e.g. reverse msg and stacktrace\n                    # stacktrace = getattr(reason, 'stacktrace', None)\n                    timeout = self._timeout\n                    entity = self.entity\n    \n                    failure = TimeoutException(\n                        f'\\n'\n                        f'\\nTimed out after {timeout}s, while waiting for:'\n                        f'\\n{entity}.{fn}'\n                        f'\\n'\n                        f'\\nReason: {reason_string}'\n                    )\n    \n>                   raise self._hook_failure(failure)\nE                   selene.core.exceptions.TimeoutException: Message: \nE                   \nE                   Timed out after 2.0s, while waiting for:\nE                   browser.element(('css selector', '.summary_value_label')).has texts ('Free Pony Express Delivery!',)\nE                   \nE                   Reason: TypeError: 'WebElement' object is not iterable\nE                   Screenshot: file://C:\\Users\\skmee\\.selene\\screenshots\\1690626939145\\1690626939146.png\nE                   PageSource: file://C:\\Users\\skmee\\.selene\\screenshots\\1690626939145\\1690626939146.html\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\wait.py:145: TimeoutException"}, "steps": [{"name": "Navigate to the checkout page and fill in valid user information", "status": "passed", "start": 1690626951924, "stop": 1690626953206}, {"name": "Verify that url redirected to second part of checkout", "status": "passed", "start": 1690626953206, "stop": 1690626953210}, {"name": "Verify second part consist of payment and delivery information", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 2.0s, while waiting for:\nbrowser.element(('css selector', '.summary_value_label')).has texts ('Free Pony Express Delivery!',)\n\nReason: TypeError: 'WebElement' object is not iterable\nScreenshot: file://C:\\Users\\skmee\\.selene\\screenshots\\1690626939145\\1690626939146.png\nPageSource: file://C:\\Users\\skmee\\.selene\\screenshots\\1690626939145\\1690626939146.html\n\n", "trace": "  File \"C:\\Users\\skmee\\PycharmProjects\\sauce_demo_UI_autotests\\tests\\test_checkout_page.py\", line 22, in test_successful_checkout\n    verify_shipping_info().\\\n    ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\skmee\\PycharmProjects\\sauce_demo_UI_autotests\\sauce_demo_UI_autotests\\model\\pages\\checkout_page.py\", line 34, in verify_shipping_info\n    browser.element('.summary_value_label').should(have.texts('Free Pony Express Delivery!'))\n  File \"C:\\Users\\skmee\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\entity.py\", line 594, in should\n    super().should(condition)\n  File \"C:\\Users\\skmee\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\entity.py\", line 127, in should\n    self.wait.for_(condition)\n  File \"C:\\Users\\skmee\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\wait.py\", line 147, in for_\n    return _(fn)\n           ^^^^^\n  File \"C:\\Users\\skmee\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\wait.py\", line 145, in _\n    raise self._hook_failure(failure)\n"}, "start": 1690626953210, "stop": 1690626955353}], "start": 1690626951923, "stop": 1690626955367, "uuid": "d850e2b5-8892-4acf-8a2a-f28d5680a590", "historyId": "07bd379d7478ab6e9b50a67d3c0cfd2f", "testCaseId": "23ab82a59cdcccaaa4563f86325204fe", "fullName": "tests.test_checkout_page#test_successful_checkout", "labels": [{"name": "feature", "value": "Successful Checkout with Valid User Information"}, {"name": "story", "value": "Verify that a user with valid information can successfully complete the checkout process and reach the order confirmation page."}, {"name": "tag", "value": "web"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_checkout_page"}, {"name": "host", "value": "LAPTOP-OFQSKCIR"}, {"name": "thread", "value": "8020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_checkout_page"}]}